title: Cloud and stuff
author: Per Andersson
description: Technical stuff


#########################################################################################
theme: "minima"
rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
